export const authStyles = {
  authHero: {
    backgroundColor: "#2f2320",
    borderRadius: 28,
    marginBottom: 18,
    padding: 22,
  },
  authEyebrow: {
    color: "#ffd7df",
    fontSize: 13,
    fontWeight: "700",
    letterSpacing: 1,
  },
  authTitle: {
    color: "#ffffff",
    fontSize: 30,
    fontWeight: "900",
    marginTop: 12,
  },
  authSubtitle: {
    color: "#f2d8d0",
    fontSize: 15,
    lineHeight: 22,
    marginTop: 10,
  },
  authCard: {
    backgroundColor: "#ffffff",
    borderColor: "#f0d7cf",
    borderRadius: 24,
    borderWidth: 1,
    padding: 18,
  },
  captchaRow: {
    alignItems: "stretch",
    flexDirection: "row",
    gap: 12,
    marginTop: 16,
  },
  captchaInput: {
    backgroundColor: "#ffffff",
    borderColor: "#f0d7cf",
    borderRadius: 16,
    borderWidth: 1,
    color: "#2f2320",
    flex: 1,
    fontSize: 16,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  captchaImage: {
    alignItems: "center",
    backgroundColor: "#fff7f3",
    borderColor: "#e9bfc4",
    borderRadius: 16,
    borderWidth: 1,
    justifyContent: "center",
    paddingHorizontal: 16,
    minWidth: 118,
  },
  captchaCode: {
    color: "#2f2320",
    fontSize: 18,
    fontWeight: "900",
    letterSpacing: 3,
  },
  captchaHint: {
    color: "#a05d6f",
    fontSize: 12,
    marginTop: 4,
  },
  authApiHint: {
    color: "#806f69",
    fontSize: 12,
    lineHeight: 18,
    marginTop: 14,
    textAlign: "center",
  },
  authPromptCard: {
    backgroundColor: "#ffffff",
    borderColor: "#f0d7cf",
    borderRadius: 24,
    borderWidth: 1,
    marginTop: 24,
    padding: 20,
  },
  authPromptTitle: {
    color: "#2f2320",
    fontSize: 20,
    fontWeight: "800",
  },
  authPromptText: {
    color: "#806f69",
    fontSize: 15,
    lineHeight: 22,
    marginTop: 10,
  },
} as const;
