export const commonStyles = {
  pageTitle: {
    color: "#2f2320",
    fontSize: 26,
    fontWeight: "800",
  },
  pageHeaderRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 12,
    marginBottom: 2,
  },
  backButton: {
    alignSelf: "flex-start",
    marginBottom: 14,
    paddingVertical: 6,
  },
  backButtonCompact: {
    paddingVertical: 6,
  },
  backButtonText: {
    color: "#a05d6f",
    fontSize: 15,
    fontWeight: "800",
  },
  input: {
    backgroundColor: "#ffffff",
    borderColor: "#f0d7cf",
    borderRadius: 16,
    borderWidth: 1,
    color: "#2f2320",
    fontSize: 16,
    marginTop: 16,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  bodyInput: {
    minHeight: 180,
  },
  longBodyInput: {
    minHeight: 340,
  },
  tagAddButton: {
    backgroundColor: "#2f2320",
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  tagAddButtonText: {
    color: "#ffffff",
    fontWeight: "800",
  },
  primaryButton: {
    alignItems: "center",
    backgroundColor: "#d94f70",
    borderRadius: 16,
    marginTop: 22,
    paddingVertical: 15,
  },
  primaryButtonText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "700",
  },
  secondaryButton: {
    alignItems: "center",
    backgroundColor: "#fff8fb",
    borderColor: "#d94f70",
    borderRadius: 16,
    borderWidth: 1,
    marginTop: 12,
    paddingVertical: 15,
  },
  secondaryButtonText: {
    color: "#d94f70",
    fontSize: 16,
    fontWeight: "800",
  },
  draftButton: {
    alignItems: "center",
    backgroundColor: "#fff1b8",
    borderColor: "#e1b84c",
    borderRadius: 16,
    borderWidth: 1,
    marginTop: 12,
    paddingVertical: 15,
  },
  draftButtonText: {
    color: "#7a5814",
    fontSize: 16,
    fontWeight: "800",
  },
  dangerButton: {
    alignItems: "center",
    backgroundColor: "#7b2c3a",
    borderRadius: 16,
    marginTop: 12,
    paddingVertical: 15,
  },
  dangerButtonText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "800",
  },
  actionRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 18,
    justifyContent: "flex-end",
  },
  actionButton: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderColor: "#f0d7cf",
    borderRadius: 16,
    borderWidth: 1,
    flex: 1,
    paddingVertical: 13,
  },
  actionButtonActive: {
    backgroundColor: "#ffe1e8",
    borderColor: "#d94f70",
  },
  actionButtonText: {
    color: "#a05d6f",
    fontWeight: "800",
  },
  tabBar: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderTopColor: "#efd8d0",
    borderTopWidth: 1,
    flexDirection: "row",
    gap: 6,
    justifyContent: "space-around",
    paddingHorizontal: 8,
    paddingVertical: 8,
  },
  tabButton: {
    alignItems: "center",
    flex: 1,
    justifyContent: "center",
    minHeight: 58,
    minWidth: 72,
    paddingHorizontal: 10,
    paddingVertical: 14,
    position: "relative",
  },
  tabBadge: {
    backgroundColor: "#d94f70",
    borderColor: "#ffffff",
    borderRadius: 5,
    borderWidth: 2,
    height: 10,
    position: "absolute",
    right: 18,
    top: 8,
    width: 10,
  },
  tabText: {
    color: "#8a7771",
    fontSize: 15,
    fontWeight: "700",
  },
  tabTextActive: {
    color: "#d94f70",
  },
  createButton: {
    alignItems: "center",
    backgroundColor: "#d94f70",
    borderRadius: 32,
    height: 64,
    justifyContent: "center",
    marginTop: -28,
    width: 64,
  },
  createButtonText: {
    color: "#ffffff",
    fontSize: 32,
    lineHeight: 36,
  },
} as const;
