import type { AppColors } from "../../theme/colors";

export function createCommonStyles(colors: AppColors) {
  return {
    pageTitle: {
      color: colors.text,
      fontSize: 26,
      fontWeight: "800",
    },
    pageHeaderRow: {
      alignItems: "center",
      flexDirection: "row",
      gap: 12,
      marginBottom: 2,
    },
    backButton: {
      alignSelf: "flex-start",
      marginBottom: 14,
      paddingVertical: 6,
    },
    backButtonCompact: {
      paddingVertical: 6,
    },
    backButtonText: {
      color: colors.primaryText,
      fontSize: 15,
      fontWeight: "800",
    },
    input: {
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderRadius: 16,
      borderWidth: 1,
      color: colors.text,
      fontSize: 16,
      marginTop: 16,
      paddingHorizontal: 16,
      paddingVertical: 14,
    },
    bodyInput: {
      minHeight: 180,
    },
    longBodyInput: {
      minHeight: 340,
    },
    tagAddButton: {
      backgroundColor: colors.text,
      borderRadius: 14,
      paddingHorizontal: 16,
      paddingVertical: 12,
    },
    tagAddButtonText: {
      color: colors.surface,
      fontWeight: "800",
    },
    primaryButton: {
      alignItems: "center",
      backgroundColor: colors.primary,
      borderRadius: 16,
      marginTop: 22,
      paddingVertical: 15,
    },
    primaryButtonText: {
      color: colors.surface,
      fontSize: 16,
      fontWeight: "700",
    },
    secondaryButton: {
      alignItems: "center",
      backgroundColor: colors.surfacePink,
      borderColor: colors.primary,
      borderRadius: 16,
      borderWidth: 1,
      marginTop: 12,
      paddingVertical: 15,
    },
    secondaryButtonText: {
      color: colors.primary,
      fontSize: 16,
      fontWeight: "800",
    },
    draftButton: {
      alignItems: "center",
      backgroundColor: colors.warning,
      borderColor: colors.warningBorder,
      borderRadius: 16,
      borderWidth: 1,
      marginTop: 12,
      paddingVertical: 15,
    },
    draftButtonText: {
      color: colors.warningText,
      fontSize: 16,
      fontWeight: "800",
    },
    dangerButton: {
      alignItems: "center",
      backgroundColor: colors.dangerText,
      borderRadius: 16,
      marginTop: 12,
      paddingVertical: 15,
    },
    dangerButtonText: {
      color: colors.surface,
      fontSize: 16,
      fontWeight: "800",
    },
    actionRow: {
      flexDirection: "row",
      gap: 10,
      marginTop: 18,
      justifyContent: "flex-end",
    },
    actionButton: {
      alignItems: "center",
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderRadius: 16,
      borderWidth: 1,
      flex: 1,
      paddingVertical: 13,
    },
    actionButtonActive: {
      backgroundColor: colors.surfacePinkStrong,
      borderColor: colors.primary,
    },
    actionButtonText: {
      color: colors.primaryText,
      fontWeight: "800",
    },
    tabBar: {
      alignItems: "center",
      backgroundColor: colors.surface,
      borderTopColor: colors.border,
      borderTopWidth: 1,
      flexDirection: "row",
      gap: 6,
      justifyContent: "space-around",
      paddingHorizontal: 8,
      paddingVertical: 8,
    },
    tabButton: {
      alignItems: "center",
      flex: 1,
      justifyContent: "center",
      minHeight: 58,
      minWidth: 72,
      paddingHorizontal: 10,
      paddingVertical: 14,
      position: "relative",
    },
    tabBadge: {
      backgroundColor: colors.primary,
      borderColor: colors.surface,
      borderRadius: 5,
      borderWidth: 2,
      height: 10,
      position: "absolute",
      right: 18,
      top: 8,
      width: 10,
    },
    tabText: {
      color: colors.textSubtle,
      fontSize: 15,
      fontWeight: "700",
    },
    tabTextActive: {
      color: colors.primary,
    },
    createButton: {
      alignItems: "center",
      backgroundColor: colors.primary,
      borderRadius: 32,
      height: 64,
      justifyContent: "center",
      marginTop: -28,
      width: 64,
    },
    createButtonText: {
      color: colors.surface,
      fontSize: 32,
      lineHeight: 36,
    },
  } as const;
}
