export const homeStyles = {
  searchInput: {
    backgroundColor: "#ffffff",
    borderColor: "#f0d7cf",
    borderRadius: 18,
    borderWidth: 1,
    color: "#2f2320",
    fontSize: 16,
    paddingHorizontal: 18,
    paddingVertical: 14,
  },
  suggestionPanel: {
    backgroundColor: "#ffffff",
    borderColor: "#f0d7cf",
    borderRadius: 18,
    borderWidth: 1,
    marginTop: 10,
    overflow: "hidden",
  },
  suggestionItem: {
    borderBottomColor: "#f6e7e2",
    borderBottomWidth: 1,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  suggestionSectionTitle: {
    color: "#8d7b75",
    fontSize: 12,
    fontWeight: "900",
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 4,
  },
  suggestionText: {
    color: "#a05d6f",
    fontWeight: "800",
  },
  suggestionMeta: {
    color: "#8d7b75",
    fontSize: 12,
    lineHeight: 17,
    marginTop: 4,
  },
  suggestionEmptyText: {
    color: "#8d7b75",
    fontSize: 13,
    padding: 16,
  },
  selectedTagRow: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderColor: "#f0d7cf",
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  selectedTagText: {
    color: "#d94f70",
    fontSize: 17,
    fontWeight: "900",
  },
  segmentedControl: {
    flexDirection: "row",
    gap: 28,
    justifyContent: "center",
    paddingHorizontal: 72,
    paddingTop: 14,
    paddingBottom: 4,
  },
  segmentButton: {
    alignItems: "center",
    flex: 1,
    paddingVertical: 8,
  },
  segmentButtonActive: {},
  segmentText: {
    color: "#8a8a8a",
    fontSize: 17,
    fontWeight: "800",
  },
  segmentTextActive: {
    color: "#1f1f1f",
  },
  segmentUnderline: {
    backgroundColor: "transparent",
    borderRadius: 999,
    height: 3,
    marginTop: 7,
    width: 24,
  },
  segmentUnderlineActive: {
    backgroundColor: "#1f1f1f",
  },
  sectionTitle: {
    color: "#2f2320",
    fontSize: 20,
    fontWeight: "700",
    marginBottom: 12,
    marginTop: 24,
  },
  sectionTitleRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
  },
} as const;
