import { StyleSheet } from "react-native";

import type { AppColors } from "../../theme/colors";

export function createProfileStyles(colors: AppColors) {
  return {
    profileHeader: {
      alignItems: "center",
      flexDirection: "row",
      gap: 14,
    },
    profileHeaderWithBackground: {
      borderRadius: 24,
      marginBottom: 14,
      minHeight: 190,
      overflow: "hidden",
    },
    profileHeaderBackgroundImage: {
      ...StyleSheet.absoluteFillObject,
    },
    profileHeaderOverlay: {
      backgroundColor: "rgba(0, 0, 0, 0.18)",
      justifyContent: "flex-end",
      minHeight: 190,
      padding: 16,
    },
    profileHeaderText: {
      flex: 1,
    },
    profileHeaderActions: {
      flexDirection: "row",
      gap: 8,
    },
    profileAnalyticsButton: {
      alignItems: "center",
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderRadius: 18,
      borderWidth: 1,
      height: 42,
      justifyContent: "center",
      width: 42,
    },
    avatar: {
      alignItems: "center",
      backgroundColor: colors.primary,
      borderRadius: 30,
      height: 60,
      justifyContent: "center",
      width: 60,
    },
    avatarImage: {
      borderRadius: 30,
      height: 60,
      width: 60,
    },
    avatarMuted: {
      alignItems: "center",
      backgroundColor: colors.textSubtle,
      borderRadius: 30,
      height: 60,
      justifyContent: "center",
      width: 60,
    },
    avatarText: {
      color: colors.surface,
      fontSize: 24,
      fontWeight: "800",
    },
    profileBio: {
      color: colors.textMuted,
      marginTop: 6,
    },
    profileStats: {
      backgroundColor: colors.surface,
      borderRadius: 20,
      flexDirection: "row",
      marginTop: 22,
      marginBottom: 16,
      paddingVertical: 18,
    },
    profileStatItem: {
      alignItems: "center",
      flex: 1,
    },
    profileStatLabelRow: {
      alignItems: "center",
      flexDirection: "row",
      gap: 6,
    },
    profileStatBadge: {
      backgroundColor: colors.primary,
      borderRadius: 5,
      height: 10,
      width: 10,
    },
    profileStatNumber: {
      color: colors.text,
      fontSize: 22,
      fontWeight: "800",
    },
    profileStatLabel: {
      color: colors.textMuted,
      marginTop: 4,
    },
    analyticsMetricGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 10,
      marginTop: 18,
    },
    analyticsMetricGridCompact: {
      flexDirection: "row",
      gap: 10,
      marginTop: 12,
    },
    analyticsMetricItemCompact: {
      alignItems: "center",
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderRadius: 14,
      borderWidth: 1,
      flex: 1,
      paddingHorizontal: 10,
      paddingVertical: 10,
    },
    analyticsMetricItem: {
      alignItems: "center",
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderRadius: 16,
      borderWidth: 1,
      flex: 1,
      minWidth: 120,
      paddingHorizontal: 12,
      paddingVertical: 14,
    },
    analyticsMetricValue: {
      color: colors.text,
      fontSize: 22,
      fontWeight: "900",
    },
    analyticsMetricLabel: {
      color: colors.textMuted,
      fontSize: 12,
      fontWeight: "700",
      marginTop: 4,
    },
    analyticsCard: {
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderRadius: 20,
      borderWidth: 1,
      marginTop: 16,
      padding: 16,
    },
    analyticsCardTitle: {
      color: colors.text,
      fontSize: 17,
      fontWeight: "800",
    },
    analyticsEmptyText: {
      color: colors.textMuted,
      lineHeight: 21,
      marginTop: 10,
    },
    analyticsBarItem: {
      marginTop: 14,
    },
    analyticsBarLabelRow: {
      alignItems: "center",
      flexDirection: "row",
      justifyContent: "space-between",
    },
    analyticsTagText: {
      color: colors.primaryText,
      fontSize: 14,
      fontWeight: "800",
    },
    analyticsCountText: {
      color: colors.textMuted,
      fontSize: 12,
      fontWeight: "700",
    },
    analyticsBarTrack: {
      backgroundColor: colors.surfaceSoft,
      borderRadius: 999,
      height: 10,
      marginTop: 8,
      overflow: "hidden",
    },
    analyticsBarFill: {
      backgroundColor: colors.primary,
      borderRadius: 999,
      height: "100%",
    },
    analyticsInsightText: {
      color: colors.textMuted,
      fontSize: 15,
      fontWeight: "700",
      lineHeight: 22,
      marginTop: 10,
    },
    analyticsTopPostItem: {
      backgroundColor: colors.surfaceSoft,
      borderColor: colors.border,
      borderRadius: 14,
      borderWidth: 1,
      marginTop: 12,
      padding: 12,
    },
    analyticsTopPostTitle: {
      color: colors.text,
      fontSize: 15,
      fontWeight: "800",
      marginBottom: 6,
    },
    profileSettingsCard: {
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderRadius: 20,
      borderWidth: 1,
      marginTop: 16,
      padding: 16,
    },
    profileBackgroundPreview: {
      borderRadius: 16,
      height: 220,
      marginTop: 12,
      width: "100%",
    },
    profileBackgroundPlaceholder: {
      alignItems: "center",
      backgroundColor: colors.surfaceSoft,
      borderColor: colors.border,
      borderRadius: 16,
      borderStyle: "dashed",
      borderWidth: 1,
      height: 220,
      justifyContent: "center",
      marginTop: 12,
    },
  } as const;
}
