export const profileStyles = {
  profileHeader: {
    alignItems: "center",
    flexDirection: "row",
    gap: 14,
  },
  profileHeaderText: {
    flex: 1,
  },
  profileHeaderActions: {
    flexDirection: "row",
    gap: 8,
  },
  profileAnalyticsButton: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderColor: "#f0d7cf",
    borderRadius: 18,
    borderWidth: 1,
    height: 42,
    justifyContent: "center",
    width: 42,
  },
  avatar: {
    alignItems: "center",
    backgroundColor: "#d94f70",
    borderRadius: 30,
    height: 60,
    justifyContent: "center",
    width: 60,
  },
  avatarMuted: {
    alignItems: "center",
    backgroundColor: "#8d7b75",
    borderRadius: 30,
    height: 60,
    justifyContent: "center",
    width: 60,
  },
  avatarText: {
    color: "#ffffff",
    fontSize: 24,
    fontWeight: "800",
  },
  profileBio: {
    color: "#806f69",
    marginTop: 6,
  },
  profileStats: {
    backgroundColor: "#ffffff",
    borderRadius: 20,
    flexDirection: "row",
    marginTop: 22,
    marginBottom: 16,
    paddingVertical: 18,
  },
  profileStatItem: {
    alignItems: "center",
    flex: 1,
  },
  profileStatLabelRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 6,
  },
  profileStatBadge: {
    backgroundColor: "#d94f70",
    borderRadius: 5,
    height: 10,
    width: 10,
  },
  profileStatNumber: {
    color: "#2f2320",
    fontSize: 22,
    fontWeight: "800",
  },
  profileStatLabel: {
    color: "#806f69",
    marginTop: 4,
  },
  analyticsMetricGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginTop: 18,
  },
  analyticsMetricGridCompact: {
    flexDirection: "row",
    gap: 10,
    marginTop: 12,
  },
  analyticsMetricItemCompact: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderColor: "#f0d7cf",
    borderRadius: 14,
    borderWidth: 1,
    flex: 1,
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  analyticsMetricItem: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderColor: "#f0d7cf",
    borderRadius: 16,
    borderWidth: 1,
    flex: 1,
    minWidth: 120,
    paddingHorizontal: 12,
    paddingVertical: 14,
  },
  analyticsMetricValue: {
    color: "#2f2320",
    fontSize: 22,
    fontWeight: "900",
  },
  analyticsMetricLabel: {
    color: "#806f69",
    fontSize: 12,
    fontWeight: "700",
    marginTop: 4,
  },
  analyticsCard: {
    backgroundColor: "#ffffff",
    borderColor: "#f0d7cf",
    borderRadius: 20,
    borderWidth: 1,
    marginTop: 16,
    padding: 16,
  },
  analyticsCardTitle: {
    color: "#2f2320",
    fontSize: 17,
    fontWeight: "800",
  },
  analyticsEmptyText: {
    color: "#806f69",
    lineHeight: 21,
    marginTop: 10,
  },
  analyticsBarItem: {
    marginTop: 14,
  },
  analyticsBarLabelRow: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  analyticsTagText: {
    color: "#a05d6f",
    fontSize: 14,
    fontWeight: "800",
  },
  analyticsCountText: {
    color: "#806f69",
    fontSize: 12,
    fontWeight: "700",
  },
  analyticsBarTrack: {
    backgroundColor: "#f6e7e2",
    borderRadius: 999,
    height: 10,
    marginTop: 8,
    overflow: "hidden",
  },
  analyticsBarFill: {
    backgroundColor: "#d94f70",
    borderRadius: 999,
    height: "100%",
  },
  analyticsInsightText: {
    color: "#5d4e49",
    fontSize: 15,
    fontWeight: "700",
    lineHeight: 22,
    marginTop: 10,
  },
  analyticsTopPostItem: {
    backgroundColor: "#fff7f3",
    borderColor: "#f0d7cf",
    borderRadius: 14,
    borderWidth: 1,
    marginTop: 12,
    padding: 12,
  },
  analyticsTopPostTitle: {
    color: "#2f2320",
    fontSize: 15,
    fontWeight: "800",
    marginBottom: 6,
  },
} as const;
