export const uploadStyles = {
  uploadBox: {
    backgroundColor: "#fffdfb",
    borderColor: "#e9bfc4",
    borderRadius: 18,
    borderStyle: "dashed",
    borderWidth: 1,
    marginTop: 16,
    padding: 18,
  },
  uploadTitle: {
    color: "#2f2320",
    fontSize: 17,
    fontWeight: "700",
  },
  uploadHint: {
    color: "#806f69",
    lineHeight: 21,
    marginTop: 8,
  },
  uploadStackedButton: {
    marginTop: 10,
  },
  uploadPreviewPanel: {
    backgroundColor: "#fffdfb",
    borderColor: "#f0d7cf",
    borderRadius: 18,
    borderWidth: 1,
    marginTop: 16,
    padding: 16,
  },
  renderedParagraphCard: {
    backgroundColor: "#ffffff",
    borderColor: "#f0d7cf",
    borderRadius: 14,
    borderWidth: 1,
    marginTop: 12,
    paddingHorizontal: 14,
    paddingBottom: 12,
  },
  editingParagraphCard: {
    backgroundColor: "#fff5f7",
    borderColor: "#e9bfc4",
    borderRadius: 14,
    borderWidth: 1,
    marginTop: 12,
    padding: 12,
  },
  rawPreviewText: {
    color: "#5d4e49",
    fontSize: 15,
    lineHeight: 22,
  },
  inlineImageList: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginTop: 14,
  },
  inlineImagePreview: {
    backgroundColor: "#f4e3dc",
    borderRadius: 16,
    height: 92,
    width: 92,
  },
  documentList: {
    gap: 8,
    marginTop: 14,
  },
  documentListItem: {
    backgroundColor: "#fff7f3",
    borderColor: "#f0d7cf",
    borderRadius: 12,
    borderWidth: 1,
    color: "#5d4e49",
    fontSize: 13,
    fontWeight: "700",
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  tagPanel: {
    backgroundColor: "#fffdfb",
    borderColor: "#f0d7cf",
    borderRadius: 18,
    borderWidth: 1,
    marginTop: 16,
    padding: 16,
  },
  tagInputRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 10,
    marginTop: 12,
  },
  tagInput: {
    backgroundColor: "#ffffff",
    borderColor: "#f0d7cf",
    borderRadius: 14,
    borderWidth: 1,
    color: "#2f2320",
    flex: 1,
    fontSize: 15,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
} as const;
