import type { AppColors } from "../../theme/colors";

export function createUploadStyles(colors: AppColors) {
  return {
    uploadBox: {
      backgroundColor: colors.surface,
      borderColor: colors.borderStrong,
      borderRadius: 18,
      borderStyle: "dashed",
      borderWidth: 1,
      marginTop: 16,
      padding: 18,
    },
    uploadTitle: {
      color: colors.text,
      fontSize: 17,
      fontWeight: "700",
    },
    uploadHint: {
      color: colors.textMuted,
      lineHeight: 21,
      marginTop: 8,
    },
    uploadStackedButton: {
      marginTop: 10,
    },
    uploadPreviewPanel: {
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderRadius: 18,
      borderWidth: 1,
      marginTop: 16,
      padding: 16,
    },
    renderedParagraphCard: {
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderRadius: 14,
      borderWidth: 1,
      marginTop: 12,
      paddingHorizontal: 14,
      paddingBottom: 12,
    },
    editingParagraphCard: {
      backgroundColor: colors.surfacePink,
      borderColor: colors.borderStrong,
      borderRadius: 14,
      borderWidth: 1,
      marginTop: 12,
      padding: 12,
    },
    rawPreviewText: {
      color: colors.textMuted,
      fontSize: 15,
      lineHeight: 22,
    },
    inlineImageList: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 10,
      marginTop: 14,
    },
    inlineImagePreview: {
      backgroundColor: "#f4e3dc",
      borderRadius: 16,
      height: 92,
      width: 92,
    },
    documentList: {
      gap: 8,
      marginTop: 14,
    },
    documentListItem: {
      backgroundColor: colors.surfaceSoft,
      borderColor: colors.border,
      borderRadius: 12,
      borderWidth: 1,
      color: colors.textMuted,
      fontSize: 13,
      fontWeight: "700",
      paddingHorizontal: 12,
      paddingVertical: 10,
    },
    tagPanel: {
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderRadius: 18,
      borderWidth: 1,
      marginTop: 16,
      padding: 16,
    },
    tagInputRow: {
      alignItems: "center",
      flexDirection: "row",
      gap: 10,
      marginTop: 12,
    },
    tagInput: {
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderRadius: 14,
      borderWidth: 1,
      color: colors.text,
      flex: 1,
      fontSize: 15,
      paddingHorizontal: 14,
      paddingVertical: 12,
    },
  } as const;
}
