import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  shell: {
    flex: 1,
    backgroundColor: '#fff7f3',
    paddingTop: 40,
  },
  app: {
    flex: 1,
    width: '100%',
    maxWidth: 720,
    alignSelf: 'center',
    backgroundColor: '#fff7f3',
  },
  pageContent: {
    padding: 20,
    paddingBottom: 112,
  },
  authPageContent: {
    padding: 20,
    paddingBottom: 112,
    paddingTop: 28,
  },
  logo: {
    color: '#2f2320',
    fontSize: 30,
    fontWeight: '800',
    marginBottom: 16,
  },
  searchInput: {
    backgroundColor: '#ffffff',
    borderColor: '#f0d7cf',
    borderRadius: 18,
    borderWidth: 1,
    color: '#2f2320',
    fontSize: 16,
    paddingHorizontal: 18,
    paddingVertical: 14,
  },
  segmentedControl: {
    backgroundColor: '#f3ded7',
    borderRadius: 16,
    flexDirection: 'row',
    gap: 8,
    marginTop: 18,
    padding: 6,
  },
  segmentButton: {
    alignItems: 'center',
    borderRadius: 12,
    flex: 1,
    paddingVertical: 10,
  },
  segmentButtonActive: {
    backgroundColor: '#ffffff',
  },
  segmentText: {
    color: '#7a6862',
    fontSize: 15,
    fontWeight: '600',
  },
  segmentTextActive: {
    color: '#d94f70',
  },
  sectionTitle: {
    color: '#2f2320',
    fontSize: 20,
    fontWeight: '700',
    marginBottom: 12,
    marginTop: 24,
  },
  card: {
    backgroundColor: '#ffffff',
    borderColor: '#f2ddd6',
    borderRadius: 20,
    borderWidth: 1,
    marginBottom: 14,
    padding: 16,
  },
  draftCard: {
    backgroundColor: '#fff8d7',
    borderColor: '#e1b84c',
  },
  deletedCard: {
    backgroundColor: '#ece8e5',
    borderColor: '#d1cac5',
    opacity: 0.72,
  },
  draftBadge: {
    alignSelf: 'flex-start',
    backgroundColor: '#e1b84c',
    borderRadius: 999,
    color: '#5c4310',
    fontSize: 12,
    fontWeight: '900',
    marginBottom: 8,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  deletedBadge: {
    alignSelf: 'flex-start',
    backgroundColor: '#8d8580',
    borderRadius: 999,
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '900',
    marginBottom: 8,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  cardTitle: {
    color: '#2f2320',
    fontSize: 18,
    fontWeight: '700',
  },
  deletedText: {
    color: '#756d68',
  },
  cardMeta: {
    color: '#8d7b75',
    marginTop: 6,
  },
  cardSummary: {
    color: '#5d4e49',
    fontSize: 15,
    lineHeight: 22,
    marginTop: 10,
  },
  cardStats: {
    flexDirection: 'row',
    gap: 14,
    marginTop: 14,
  },
  statText: {
    color: '#a05d6f',
    fontSize: 13,
  },
  pageTitle: {
    color: '#2f2320',
    fontSize: 26,
    fontWeight: '800',
  },
  pageHeaderRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    marginBottom: 2,
  },
  backButton: {
    alignSelf: 'flex-start',
    marginBottom: 14,
    paddingVertical: 6,
  },
  backButtonCompact: {
    paddingVertical: 6,
  },
  backButtonText: {
    color: '#a05d6f',
    fontSize: 15,
    fontWeight: '800',
  },
  input: {
    backgroundColor: '#ffffff',
    borderColor: '#f0d7cf',
    borderRadius: 16,
    borderWidth: 1,
    color: '#2f2320',
    fontSize: 16,
    marginTop: 16,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  bodyInput: {
    minHeight: 180,
  },
  longBodyInput: {
    minHeight: 340,
  },
  uploadBox: {
    backgroundColor: '#fffdfb',
    borderColor: '#e9bfc4',
    borderRadius: 18,
    borderStyle: 'dashed',
    borderWidth: 1,
    marginTop: 16,
    padding: 18,
  },
  uploadTitle: {
    color: '#2f2320',
    fontSize: 17,
    fontWeight: '700',
  },
  uploadHint: {
    color: '#806f69',
    lineHeight: 21,
    marginTop: 8,
  },
  tagPanel: {
    backgroundColor: '#fffdfb',
    borderColor: '#f0d7cf',
    borderRadius: 18,
    borderWidth: 1,
    marginTop: 16,
    padding: 16,
  },
  tagInputRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    marginTop: 12,
  },
  tagInput: {
    backgroundColor: '#ffffff',
    borderColor: '#f0d7cf',
    borderRadius: 14,
    borderWidth: 1,
    color: '#2f2320',
    flex: 1,
    fontSize: 15,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  tagAddButton: {
    backgroundColor: '#2f2320',
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  tagAddButtonText: {
    color: '#ffffff',
    fontWeight: '800',
  },
  tagList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 14,
  },
  tagChip: {
    backgroundColor: '#f3ded7',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  tagChipText: {
    color: '#a05d6f',
    fontWeight: '700',
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: '#d94f70',
    borderRadius: 16,
    marginTop: 22,
    paddingVertical: 15,
  },
  primaryButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '700',
  },
  draftButton: {
    alignItems: 'center',
    backgroundColor: '#fff1b8',
    borderColor: '#e1b84c',
    borderRadius: 16,
    borderWidth: 1,
    marginTop: 12,
    paddingVertical: 15,
  },
  draftButtonText: {
    color: '#7a5814',
    fontSize: 16,
    fontWeight: '800',
  },
  dangerButton: {
    alignItems: 'center',
    backgroundColor: '#7b2c3a',
    borderRadius: 16,
    marginTop: 12,
    paddingVertical: 15,
  },
  dangerButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '800',
  },
  actionRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 18,
    justifyContent: 'flex-end',
  },
  actionButton: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: '#f0d7cf',
    borderRadius: 16,
    borderWidth: 1,
    flex: 1,
    paddingVertical: 13,
  },
  actionButtonActive: {
    backgroundColor: '#ffe1e8',
    borderColor: '#d94f70',
  },
  actionButtonText: {
    color: '#a05d6f',
    fontWeight: '800',
  },
  blogBody: {
    color: '#3d302c',
    fontSize: 16,
    lineHeight: 26,
    marginTop: 20,
  },
  authHero: {
    backgroundColor: '#2f2320',
    borderRadius: 28,
    marginBottom: 18,
    padding: 22,
  },
  authEyebrow: {
    color: '#ffd7df',
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 1,
  },
  authTitle: {
    color: '#ffffff',
    fontSize: 30,
    fontWeight: '900',
    marginTop: 12,
  },
  authSubtitle: {
    color: '#f2d8d0',
    fontSize: 15,
    lineHeight: 22,
    marginTop: 10,
  },
  authCard: {
    backgroundColor: '#ffffff',
    borderColor: '#f0d7cf',
    borderRadius: 24,
    borderWidth: 1,
    padding: 18,
  },
  captchaRow: {
    alignItems: 'stretch',
    flexDirection: 'row',
    gap: 12,
    marginTop: 16,
  },
  captchaInput: {
    backgroundColor: '#ffffff',
    borderColor: '#f0d7cf',
    borderRadius: 16,
    borderWidth: 1,
    color: '#2f2320',
    flex: 1,
    fontSize: 16,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  captchaImage: {
    alignItems: 'center',
    backgroundColor: '#fff7f3',
    borderColor: '#e9bfc4',
    borderRadius: 16,
    borderWidth: 1,
    justifyContent: 'center',
    paddingHorizontal: 16,
    minWidth: 118,
  },
  captchaCode: {
    color: '#2f2320',
    fontSize: 18,
    fontWeight: '900',
    letterSpacing: 3,
  },
  captchaHint: {
    color: '#a05d6f',
    fontSize: 12,
    marginTop: 4,
  },
  authApiHint: {
    color: '#806f69',
    fontSize: 12,
    lineHeight: 18,
    marginTop: 14,
    textAlign: 'center',
  },
  authPromptCard: {
    backgroundColor: '#ffffff',
    borderColor: '#f0d7cf',
    borderRadius: 24,
    borderWidth: 1,
    marginTop: 24,
    padding: 20,
  },
  authPromptTitle: {
    color: '#2f2320',
    fontSize: 20,
    fontWeight: '800',
  },
  authPromptText: {
    color: '#806f69',
    fontSize: 15,
    lineHeight: 22,
    marginTop: 10,
  },
  profileHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 14,
  },
  avatar: {
    alignItems: 'center',
    backgroundColor: '#d94f70',
    borderRadius: 30,
    height: 60,
    justifyContent: 'center',
    width: 60,
  },
  avatarMuted: {
    alignItems: 'center',
    backgroundColor: '#8d7b75',
    borderRadius: 30,
    height: 60,
    justifyContent: 'center',
    width: 60,
  },
  avatarText: {
    color: '#ffffff',
    fontSize: 24,
    fontWeight: '800',
  },
  profileBio: {
    color: '#806f69',
    marginTop: 6,
  },
  profileStats: {
    backgroundColor: '#ffffff',
    borderRadius: 20,
    flexDirection: 'row',
    marginTop: 22,
    paddingVertical: 18,
  },
  profileStatItem: {
    alignItems: 'center',
    flex: 1,
  },
  profileStatNumber: {
    color: '#2f2320',
    fontSize: 22,
    fontWeight: '800',
  },
  profileStatLabel: {
    color: '#806f69',
    marginTop: 4,
  },
  tabBar: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: '#efd8d0',
    borderRadius: 24,
    borderWidth: 1,
    bottom: 18,
    flexDirection: 'row',
    gap: 18,
    justifyContent: 'space-around',
    left: 20,
    paddingHorizontal: 18,
    paddingVertical: 12,
    position: 'absolute',
    right: 20,
  },
  tabButton: {
    alignItems: 'center',
    flex: 1,
    paddingVertical: 10,
  },
  tabText: {
    color: '#8a7771',
    fontSize: 15,
    fontWeight: '700',
  },
  tabTextActive: {
    color: '#d94f70',
  },
  createButton: {
    alignItems: 'center',
    backgroundColor: '#d94f70',
    borderRadius: 28,
    height: 56,
    justifyContent: 'center',
    marginTop: -24,
    width: 56,
  },
  createButtonText: {
    color: '#ffffff',
    fontSize: 32,
    lineHeight: 36,
  },
});
