import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  gestureRoot: {
    flex: 1,
  },
  
  shell: {
    flex: 1,
    backgroundColor: '#f5f5f5',
    paddingTop: 40,
  },
  app: {
    flex: 1,
    width: '100%',
    maxWidth: 720,
    alignSelf: 'center',
    backgroundColor: '#f5f5f5',
  },
  pageContent: {
    backgroundColor: '#f5f5f5',
    padding: 20,
    paddingBottom: 24,
  },
  blogPageContent: {
    backgroundColor: '#ffffff',
  },
  homeScreen: {
    backgroundColor: '#f5f5f5',
    flex: 1,
  },
  authPageContent: {
    backgroundColor: '#f5f5f5',
    padding: 20,
    paddingBottom: 24,
    paddingTop: 28,
  },
  logo: {
    color: '#2f2320',
    fontSize: 30,
    fontWeight: '800',
    marginBottom: 16,
  },
  searchInput: {
    backgroundColor: '#ffffff',
    borderColor: '#f0d7cf',
    borderRadius: 18,
    borderWidth: 1,
    color: '#2f2320',
    fontSize: 16,
    paddingHorizontal: 18,
    paddingVertical: 14,
  },
  suggestionPanel: {
    backgroundColor: '#ffffff',
    borderColor: '#f0d7cf',
    borderRadius: 18,
    borderWidth: 1,
    marginTop: 10,
    overflow: 'hidden',
  },
  suggestionItem: {
    borderBottomColor: '#f6e7e2',
    borderBottomWidth: 1,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  suggestionSectionTitle: {
    color: '#8d7b75',
    fontSize: 12,
    fontWeight: '900',
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 4,
  },
  suggestionText: {
    color: '#a05d6f',
    fontWeight: '800',
  },
  suggestionMeta: {
    color: '#8d7b75',
    fontSize: 12,
    lineHeight: 17,
    marginTop: 4,
  },
  suggestionEmptyText: {
    color: '#8d7b75',
    fontSize: 13,
    padding: 16,
  },
  selectedTagRow: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: '#f0d7cf',
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  selectedTagText: {
    color: '#d94f70',
    fontSize: 17,
    fontWeight: '900',
  },
  segmentedControl: {
    flexDirection: 'row',
    gap: 28,
    justifyContent: 'center',
    paddingHorizontal: 72,
    paddingTop: 14,
    paddingBottom: 4,
  },
  segmentButton: {
    alignItems: 'center',
    flex: 1,
    paddingVertical: 8,
  },
  segmentButtonActive: {
  },
  segmentText: {
    color: '#8a8a8a',
    fontSize: 17,
    fontWeight: '800',
  },
  segmentTextActive: {
    color: '#1f1f1f',
  },
  segmentUnderline: {
    backgroundColor: 'transparent',
    borderRadius: 999,
    height: 3,
    marginTop: 7,
    width: 24,
  },
  segmentUnderlineActive: {
    backgroundColor: '#1f1f1f',
  },
  sectionTitle: {
    color: '#2f2320',
    fontSize: 20,
    fontWeight: '700',
    marginBottom: 12,
    marginTop: 24,
  },
  sectionTitleRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  commentNotificationHint: {
    color: '#a05d6f',
    fontSize: 12,
    fontWeight: '700',
    marginBottom: 12,
  },
  notificationCard: {
    backgroundColor: '#fff8fb',
    borderColor: '#efc6d2',
    borderRadius: 18,
    borderWidth: 1,
    marginTop: 12,
    padding: 16,
  },
  notificationCardRead: {
    backgroundColor: '#f1efee',
    borderColor: '#d8d2cf',
  },
  notificationTitleRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'space-between',
  },
  notificationTitle: {
    color: '#2f2320',
    flex: 1,
    fontSize: 16,
    fontWeight: '700',
  },
  notificationMeta: {
    color: '#a05d6f',
    fontSize: 12,
    marginTop: 8,
  },
  notificationMetaRead: {
    color: '#8d8580',
  },
  card: {
    backgroundColor: '#ffffff',
    borderColor: '#f2ddd6',
    borderRadius: 20,
    borderWidth: 1,
    marginBottom: 14,
    padding: 16,
  },
  cardPressed: {
    opacity: 0.82,
    transform: [{ scale: 0.99 }],
  },
  postCardActionMenu: {
    alignSelf: 'flex-end',
    backgroundColor: '#ffffff',
    borderColor: '#e9bfc4',
    borderRadius: 999,
    borderWidth: 1,
    marginBottom: 8,
    padding: 4,
    shadowColor: '#2f2320',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 10,
  },
  postCardActionMenuRow: {
    alignSelf: 'flex-end',
    backgroundColor: '#ffffff',
    borderColor: '#e9bfc4',
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginBottom: 8,
    padding: 4,
  },
  postCardActionButton: {
    backgroundColor: '#fff0f2',
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  postCardActionButtonMuted: {
    backgroundColor: '#fff7f3',
  },
  postCardActionText: {
    color: '#a05d6f',
    fontSize: 12,
    fontWeight: '900',
  },
  postCardActionDangerText: {
    color: '#7b2c3a',
  },
  postCardDeleteButton: {
    backgroundColor: '#e84040',
  },
  postCardDeleteText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '900',
  },
  confirmOverlay: {
    alignItems: 'center',
    backgroundColor: 'rgba(47, 35, 32, 0.42)',
    flex: 1,
    justifyContent: 'center',
    padding: 24,
  },
  confirmDialog: {
    alignSelf: 'center',
    backgroundColor: '#ffffff',
    borderRadius: 24,
    maxWidth: 420,
    padding: 20,
    width: '100%',
  },
  confirmTitle: {
    color: '#2f2320',
    fontSize: 20,
    fontWeight: '900',
  },
  confirmMessage: {
    color: '#806f69',
    fontSize: 15,
    lineHeight: 22,
    marginTop: 10,
  },
  confirmActionRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 18,
  },
  confirmButton: {
    alignItems: 'center',
    borderRadius: 16,
    flex: 1,
    paddingVertical: 13,
  },
  confirmCancelButton: {
    backgroundColor: '#f1efee',
  },
  confirmDangerButton: {
    backgroundColor: '#e84040',
  },
  confirmCancelText: {
    color: '#5d4e49',
    fontWeight: '900',
  },
  confirmDangerText: {
    color: '#ffffff',
    fontWeight: '900',
  },
  draftCard: {
    backgroundColor: '#fff8d7',
    borderColor: '#e1b84c',
  },
  deletedCard: {
    backgroundColor: '#ece8e5',
    borderColor: '#d1cac5',
    opacity: 0.72,
  },
  draftBadge: {
    alignSelf: 'flex-start',
    backgroundColor: '#e1b84c',
    borderRadius: 999,
    color: '#5c4310',
    fontSize: 12,
    fontWeight: '900',
    marginBottom: 8,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  deletedBadge: {
    alignSelf: 'flex-start',
    backgroundColor: '#8d8580',
    borderRadius: 999,
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '900',
    marginBottom: 8,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  cardTitle: {
    color: '#2f2320',
    fontSize: 18,
    fontWeight: '700',
  },
  cardTitleRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  cardNotificationDot: {
    backgroundColor: '#d94f70',
    borderRadius: 5,
    height: 10,
    width: 10,
  },
  deletedText: {
    color: '#756d68',
  },
  cardMeta: {
    color: '#8d7b75',
    marginTop: 6,
  },
  cardAuthor: {
    color: '#a05d6f',
    marginTop: 6,
  },
  cardSummary: {
    color: '#5d4e49',
    fontSize: 15,
    lineHeight: 22,
    marginTop: 10,
  },
  cardMarkdownSummary: {
    marginTop: 10,
  },
  cardStats: {
    flexDirection: 'row',
    gap: 14,
    marginTop: 14,
  },
  skeletonBlock: {
    backgroundColor: '#f0d7cf',
    borderRadius: 999,
  },
  skeletonGapSmall: {
    height: 8,
  },
  skeletonGapMedium: {
    height: 12,
  },
  skeletonGapLarge: {
    height: 22,
  },
  skeletonTagRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 16,
  },
  skeletonHero: {
    aspectRatio: 1.6,
    backgroundColor: '#f0d7cf',
    borderRadius: 18,
    marginBottom: 20,
    marginTop: 18,
    width: '100%',
  },
  statText: {
    color: '#a05d6f',
    fontSize: 13,
  },
  collectionFavoriteCard: {
    backgroundColor: '#f4fbff',
    borderColor: '#94c8df',
  },
  collectionBadge: {
    alignSelf: 'flex-start',
    backgroundColor: '#d9f0fb',
    borderRadius: 999,
    color: '#26708f',
    fontSize: 12,
    fontWeight: '900',
    marginBottom: 8,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  compactActionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 14,
  },
  compactActionButton: {
    alignItems: 'center',
    backgroundColor: '#fff7f3',
    borderColor: '#f0d7cf',
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: 'row',
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  compactDangerButton: {
    backgroundColor: '#fff0f2',
    borderColor: '#e4a3ad',
  },
  compactActionText: {
    color: '#a05d6f',
    fontSize: 12,
    fontWeight: '800',
  },
  compactDangerText: {
    color: '#7b2c3a',
  },
  movePostPanel: {
    backgroundColor: '#fffaf6',
    borderColor: '#f1c8b6',
    borderRadius: 16,
    borderStyle: 'dashed',
    borderWidth: 1,
    marginBottom: 14,
    marginTop: -6,
    padding: 12,
  },
  movePostPanelOpen: {
    backgroundColor: '#fff4ec',
  },
  movePostTitleRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  movePostTitle: {
    color: '#8d4b3c',
    fontSize: 13,
    fontWeight: '800',
  },
  movePostHint: {
    color: '#9b756b',
    fontSize: 12,
    lineHeight: 18,
  },
  movePostCollectionList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  pageTitle: {
    color: '#2f2320',
    fontSize: 26,
    fontWeight: '800',
  },
  pageHeaderRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    marginBottom: 2,
  },
  backButton: {
    alignSelf: 'flex-start',
    marginBottom: 14,
    paddingVertical: 6,
  },
  backButtonCompact: {
    paddingVertical: 6,
  },
  backButtonText: {
    color: '#a05d6f',
    fontSize: 15,
    fontWeight: '800',
  },
  input: {
    backgroundColor: '#ffffff',
    borderColor: '#f0d7cf',
    borderRadius: 16,
    borderWidth: 1,
    color: '#2f2320',
    fontSize: 16,
    marginTop: 16,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  bodyInput: {
    minHeight: 180,
  },
  longBodyInput: {
    minHeight: 340,
  },
  uploadBox: {
    backgroundColor: '#fffdfb',
    borderColor: '#e9bfc4',
    borderRadius: 18,
    borderStyle: 'dashed',
    borderWidth: 1,
    marginTop: 16,
    padding: 18,
  },
  uploadTitle: {
    color: '#2f2320',
    fontSize: 17,
    fontWeight: '700',
  },
  uploadHint: {
    color: '#806f69',
    lineHeight: 21,
    marginTop: 8,
  },
  uploadStackedButton: {
    marginTop: 10,
  },
  uploadPreviewPanel: {
    backgroundColor: '#fffdfb',
    borderColor: '#f0d7cf',
    borderRadius: 18,
    borderWidth: 1,
    marginTop: 16,
    padding: 16,
  },
  renderedParagraphCard: {
    backgroundColor: '#ffffff',
    borderColor: '#f0d7cf',
    borderRadius: 14,
    borderWidth: 1,
    marginTop: 12,
    paddingHorizontal: 14,
    paddingBottom: 12,
  },
  editingParagraphCard: {
    backgroundColor: '#fff5f7',
    borderColor: '#e9bfc4',
    borderRadius: 14,
    borderWidth: 1,
    marginTop: 12,
    padding: 12,
  },
  editingParagraphHint: {
    color: '#a05d6f',
    fontSize: 13,
    fontWeight: '700',
  },
  rawPreviewText: {
    color: '#5d4e49',
    fontSize: 15,
    lineHeight: 22,
  },
  inlineImageList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 14,
  },
  inlineImagePreview: {
    backgroundColor: '#f4e3dc',
    borderRadius: 16,
    height: 92,
    width: 92,
  },
  documentList: {
    gap: 8,
    marginTop: 14,
  },
  documentListItem: {
    backgroundColor: '#fff7f3',
    borderColor: '#f0d7cf',
    borderRadius: 12,
    borderWidth: 1,
    color: '#5d4e49',
    fontSize: 13,
    fontWeight: '700',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  tagPanel: {
    backgroundColor: '#fffdfb',
    borderColor: '#f0d7cf',
    borderRadius: 18,
    borderWidth: 1,
    marginTop: 16,
    padding: 16,
  },
  tagInputRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    marginTop: 12,
  },
  tagInput: {
    backgroundColor: '#ffffff',
    borderColor: '#f0d7cf',
    borderRadius: 14,
    borderWidth: 1,
    color: '#2f2320',
    flex: 1,
    fontSize: 15,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  tagAddButton: {
    backgroundColor: '#2f2320',
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  tagAddButtonText: {
    color: '#ffffff',
    fontWeight: '800',
  },
  tagList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 14,
  },
  tagChip: {
    backgroundColor: '#f3ded7',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  tagChipText: {
    color: '#a05d6f',
    fontWeight: '700',
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: '#d94f70',
    borderRadius: 16,
    marginTop: 22,
    paddingVertical: 15,
  },
  primaryButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '700',
  },
  secondaryButton: {
    alignItems: 'center',
    backgroundColor: '#fff8fb',
    borderColor: '#d94f70',
    borderRadius: 16,
    borderWidth: 1,
    marginTop: 12,
    paddingVertical: 15,
  },
  secondaryButtonText: {
    color: '#d94f70',
    fontSize: 16,
    fontWeight: '800',
  },
  messagePanel: {
    marginTop: 8,
  },
  messageUserItem: {
    backgroundColor: '#fff8fb',
    borderColor: '#efd1da',
    borderRadius: 16,
    borderWidth: 1,
    marginTop: 10,
    padding: 14,
  },
  messageConversationCard: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderRadius: 18,
    flexDirection: 'row',
    gap: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    width: '100%',
  },
  messageConversationMetaRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  swipeConversationContainer: {
    borderRadius: 18,
    marginBottom: 10,
    overflow: 'hidden',
    position: 'relative',
  },
  swipeDeleteButton: {
    alignItems: 'center',
    backgroundColor: '#e84040',
    justifyContent: 'center',
    width: 86,
  },
  swipeDeleteText: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '900',
  },
  chatScreen: {
    flex: 1,
    paddingBottom: 18,
  },
  chatHeader: {
    backgroundColor: '#f5f5f5',
    borderBottomColor: '#f0d7cf',
    borderBottomWidth: 1,
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 14,
  },
  chatTitle: {
    color: '#2f2320',
    fontSize: 22,
    fontWeight: '800',
  },
  chatSubtitle: {
    color: '#8d7b75',
    marginTop: 4,
  },
  chatListContent: {
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 12,
  },
  chatTimeDivider: {
    color: '#8d7b75',
    fontSize: 12,
    fontWeight: '600',
    marginBottom: 14,
    marginTop: 4,
    textAlign: 'center',
  },
  messageUnreadBadge: {
    alignItems: 'center',
    backgroundColor: '#d94f70',
    borderRadius: 999,
    height: 24,
    justifyContent: 'center',
    minWidth: 24,
    paddingHorizontal: 8,
  },
  messageUnreadText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '800',
  },
  messageSearchRow: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderRadius: 999,
    flexDirection: 'row',
    gap: 10,
    marginTop: 16,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  messageSearchInput: {
    color: '#2f2320',
    flex: 1,
    fontSize: 15,
  },
  messageSearchResults: {
    backgroundColor: '#ffffff',
    borderRadius: 18,
    marginTop: 10,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  messageUserRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    paddingVertical: 12,
  },
  messageAvatar: {
    backgroundColor: '#f0d7cf',
    borderRadius: 24,
    height: 48,
    width: 48,
  },
  messageAvatarFallback: {
    alignItems: 'center',
    backgroundColor: '#ffe1e8',
    borderRadius: 24,
    height: 48,
    justifyContent: 'center',
    width: 48,
  },
  messageAvatarText: {
    color: '#d94f70',
    fontSize: 18,
    fontWeight: '900',
  },
  followingMessageScroller: {
    gap: 12,
    paddingBottom: 6,
    paddingTop: 8,
  },
  followingMessageItem: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderRadius: 18,
    paddingHorizontal: 12,
    paddingVertical: 12,
    width: 92,
  },
  followingMessageName: {
    color: '#2f2320',
    fontSize: 13,
    fontWeight: '800',
    marginTop: 8,
    maxWidth: 72,
  },
  followingMessageUsername: {
    color: '#a89994',
    fontSize: 11,
    marginTop: 3,
    maxWidth: 72,
  },
  messageRowTextBlock: {
    flex: 1,
  },
  messageLastText: {
    color: '#806f69',
    fontSize: 13,
    marginTop: 5,
  },
  messageConversationSideMeta: {
    alignItems: 'flex-end',
    gap: 8,
  },
  messageTimeText: {
    color: '#a89994',
    fontSize: 11,
    maxWidth: 92,
  },
  messageCenterSubtitle: {
    color: '#806f69',
    fontSize: 14,
    lineHeight: 20,
    marginTop: 8,
  },
  messageShortcutGrid: {
    backgroundColor: '#ffffff',
    borderRadius: 22,
    flexDirection: 'row',
    gap: 10,
    marginTop: 18,
    padding: 14,
  },
  messageShortcutCard: {
    alignItems: 'center',
    flex: 1,
    gap: 8,
    paddingVertical: 8,
  },
  messageShortcutIconWrap: {
    alignItems: 'center',
    backgroundColor: '#fff0f4',
    borderRadius: 20,
    height: 52,
    justifyContent: 'center',
    position: 'relative',
    width: 52,
  },
  messageShortcutDot: {
    backgroundColor: '#d94f70',
    borderColor: '#ffffff',
    borderRadius: 6,
    borderWidth: 2,
    height: 12,
    position: 'absolute',
    right: 4,
    top: 4,
    width: 12,
  },
  messageShortcutLabel: {
    color: '#2f2320',
    fontSize: 13,
    fontWeight: '800',
  },
  aiChatPanel: {
    alignItems: 'center',
    backgroundColor: '#fffdfb',
    borderColor: '#f0d7cf',
    borderRadius: 22,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 14,
    marginTop: 18,
    padding: 16,
  },
  aiChatIconBubble: {
    alignItems: 'center',
    backgroundColor: '#fff0f4',
    borderRadius: 24,
    height: 56,
    justifyContent: 'center',
    width: 56,
  },
  aiChatTextBlock: {
    flex: 1,
  },
  aiChatTitle: {
    color: '#2f2320',
    fontSize: 17,
    fontWeight: '900',
  },
  aiChatDescription: {
    color: '#806f69',
    fontSize: 13,
    lineHeight: 19,
    marginTop: 6,
  },
  messageBubble: {
    borderRadius: 18,
    marginBottom: 12,
    maxWidth: '82%',
    padding: 14,
  },
  messageBubbleMine: {
    alignSelf: 'flex-end',
    backgroundColor: '#ffe1e8',
  },
  messageBubbleOther: {
    alignSelf: 'flex-start',
    backgroundColor: '#ffffff',
    borderColor: '#f0d7cf',
    borderWidth: 1,
  },
  messageBubbleText: {
    color: '#2f2320',
    fontSize: 15,
    lineHeight: 22,
  },
  messageBubbleMeta: {
    color: '#8d7b75',
    fontSize: 11,
    marginTop: 8,
  },
  messageComposer: {
    marginTop: 18,
  },
  chatComposerBar: {
    alignItems: 'flex-end',
    backgroundColor: '#fffdfb',
    borderTopColor: '#f0d7cf',
    borderTopWidth: 1,
    flexDirection: 'row',
    gap: 10,
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 8,
  },
  chatComposerInput: {
    backgroundColor: '#ffffff',
    borderColor: '#f0d7cf',
    borderRadius: 18,
    borderWidth: 1,
    color: '#2f2320',
    flex: 1,
    fontSize: 15,
    maxHeight: 120,
    minHeight: 48,
    paddingHorizontal: 14,
    paddingVertical: 12,
    textAlignVertical: 'top',
  },
  chatSendButton: {
    alignItems: 'center',
    alignSelf: 'flex-end',
    backgroundColor: '#d94f70',
    borderRadius: 16,
    justifyContent: 'center',
    minHeight: 48,
    paddingHorizontal: 18,
  },
  chatComposerHint: {
    paddingHorizontal: 20,
    textAlign: 'left',
  },
  draftButton: {
    alignItems: 'center',
    backgroundColor: '#fff1b8',
    borderColor: '#e1b84c',
    borderRadius: 16,
    borderWidth: 1,
    marginTop: 12,
    paddingVertical: 15,
  },
  draftButtonText: {
    color: '#7a5814',
    fontSize: 16,
    fontWeight: '800',
  },
  dangerButton: {
    alignItems: 'center',
    backgroundColor: '#7b2c3a',
    borderRadius: 16,
    marginTop: 12,
    paddingVertical: 15,
  },
  dangerButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '800',
  },
  actionRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 18,
    justifyContent: 'flex-end',
  },
  actionButton: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: '#f0d7cf',
    borderRadius: 16,
    borderWidth: 1,
    flex: 1,
    paddingVertical: 13,
  },
  actionButtonActive: {
    backgroundColor: '#ffe1e8',
    borderColor: '#d94f70',
  },
  actionButtonText: {
    color: '#a05d6f',
    fontWeight: '800',
  },
  blogBody: {
    color: '#3d302c',
    fontSize: 16,
    lineHeight: 26,
    marginTop: 20,
  },
  blogImage: {
    alignSelf: 'center',
    backgroundColor: '#f4e3dc',
    borderRadius: 18,
    maxHeight: 420,
    width: '100%',
  },
  imagePreviewOverlay: {
    alignItems: 'center',
    backgroundColor: 'rgba(47, 35, 32, 0.92)',
    flex: 1,
    justifyContent: 'center',
    padding: 18,
  },
  imagePreview: {
    height: '82%',
    width: '100%',
  },
  imagePreviewHint: {
    color: '#fff7f3',
    fontSize: 13,
    fontWeight: '700',
    marginTop: 12,
  },
  commentSection: {
    borderTopColor: '#f0d7cf',
    borderTopWidth: 1,
    marginTop: 28,
    paddingTop: 4,
  },
  commentScreenContainer: {
    flex: 1,
  },
  blogScreenContainer: {
    backgroundColor: '#ffffff',
  },
  blogBottomBarHost: {
    backgroundColor: '#ffffff',
    borderTopColor: '#f0d7cf',
    borderTopWidth: 1,
    paddingBottom: 10,
    paddingHorizontal: 14,
    paddingTop: 10,
  },
  blogBottomBar: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  blogReplyTargetRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  blogReplyTargetText: {
    color: '#806f69',
    fontSize: 13,
    fontWeight: '800',
  },
  blogReplyCancelText: {
    color: '#d94f70',
    fontSize: 13,
    fontWeight: '900',
  },
  blogBottomCommentInput: {
    backgroundColor: '#ffffff',
    borderColor: '#f0d7cf',
    borderRadius: 999,
    borderWidth: 1,
    color: '#2f2320',
    flex: 1,
    fontSize: 14,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  blogBottomActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  blogBottomActionButton: {
    alignItems: 'center',
    minWidth: 34,
  },
  blogBottomActionText: {
    color: '#7a6862',
    fontSize: 11,
    fontWeight: '800',
    marginTop: 2,
  },
  commentComposer: {
    backgroundColor: '#fffdfb',
    borderColor: '#f0d7cf',
    borderRadius: 20,
    borderWidth: 1,
    marginBottom: 16,
    padding: 14,
  },
  commentInput: {
    minHeight: 82,
    textAlignVertical: 'top',
  },
  commentCard: {
    backgroundColor: '#ffffff',
    borderColor: '#f2ddd6',
    borderRadius: 18,
    borderWidth: 1,
    marginTop: 12,
    padding: 14,
  },
  commentThread: {
    marginTop: 12,
  },
  commentReplyThread: {
    marginLeft: 18,
  },
  commentReplyCard: {
    backgroundColor: '#fff8f5',
  },
  commentFocusedCard: {
    backgroundColor: '#fff0f5',
    borderColor: '#d94f70',
  },
  commentHeader: {
    alignItems: 'baseline',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    justifyContent: 'space-between',
  },
  commentBody: {
    color: '#3d302c',
    fontSize: 15,
    lineHeight: 22,
    marginTop: 10,
  },
  replyComposer: {
    marginTop: 12,
  },
  authHero: {
    backgroundColor: '#2f2320',
    borderRadius: 28,
    marginBottom: 18,
    padding: 22,
  },
  authEyebrow: {
    color: '#ffd7df',
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 1,
  },
  authTitle: {
    color: '#ffffff',
    fontSize: 30,
    fontWeight: '900',
    marginTop: 12,
  },
  authSubtitle: {
    color: '#f2d8d0',
    fontSize: 15,
    lineHeight: 22,
    marginTop: 10,
  },
  authCard: {
    backgroundColor: '#ffffff',
    borderColor: '#f0d7cf',
    borderRadius: 24,
    borderWidth: 1,
    padding: 18,
  },
  captchaRow: {
    alignItems: 'stretch',
    flexDirection: 'row',
    gap: 12,
    marginTop: 16,
  },
  captchaInput: {
    backgroundColor: '#ffffff',
    borderColor: '#f0d7cf',
    borderRadius: 16,
    borderWidth: 1,
    color: '#2f2320',
    flex: 1,
    fontSize: 16,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  captchaImage: {
    alignItems: 'center',
    backgroundColor: '#fff7f3',
    borderColor: '#e9bfc4',
    borderRadius: 16,
    borderWidth: 1,
    justifyContent: 'center',
    paddingHorizontal: 16,
    minWidth: 118,
  },
  captchaCode: {
    color: '#2f2320',
    fontSize: 18,
    fontWeight: '900',
    letterSpacing: 3,
  },
  captchaHint: {
    color: '#a05d6f',
    fontSize: 12,
    marginTop: 4,
  },
  authApiHint: {
    color: '#806f69',
    fontSize: 12,
    lineHeight: 18,
    marginTop: 14,
    textAlign: 'center',
  },
  authPromptCard: {
    backgroundColor: '#ffffff',
    borderColor: '#f0d7cf',
    borderRadius: 24,
    borderWidth: 1,
    marginTop: 24,
    padding: 20,
  },
  authPromptTitle: {
    color: '#2f2320',
    fontSize: 20,
    fontWeight: '800',
  },
  authPromptText: {
    color: '#806f69',
    fontSize: 15,
    lineHeight: 22,
    marginTop: 10,
  },
  profileHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 14,
  },
  profileHeaderText: {
    flex: 1,
  },
  profileAnalyticsButton: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: '#f0d7cf',
    borderRadius: 18,
    borderWidth: 1,
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  avatar: {
    alignItems: 'center',
    backgroundColor: '#d94f70',
    borderRadius: 30,
    height: 60,
    justifyContent: 'center',
    width: 60,
  },
  avatarMuted: {
    alignItems: 'center',
    backgroundColor: '#8d7b75',
    borderRadius: 30,
    height: 60,
    justifyContent: 'center',
    width: 60,
  },
  avatarText: {
    color: '#ffffff',
    fontSize: 24,
    fontWeight: '800',
  },
  profileBio: {
    color: '#806f69',
    marginTop: 6,
  },
  profileStats: {
    backgroundColor: '#ffffff',
    borderRadius: 20,
    flexDirection: 'row',
    marginTop: 22,
    marginBottom: 16,
    paddingVertical: 18,
  },
  profileStatItem: {
    alignItems: 'center',
    flex: 1,
  },
  profileStatLabelRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
  },
  profileStatBadge: {
    backgroundColor: '#d94f70',
    borderRadius: 5,
    height: 10,
    width: 10,
  },
  profileStatNumber: {
    color: '#2f2320',
    fontSize: 22,
    fontWeight: '800',
  },
  profileStatLabel: {
    color: '#806f69',
    marginTop: 4,
  },
  analyticsMetricGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 18,
  },
  analyticsMetricGridCompact: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 12,
  },
  analyticsMetricItemCompact: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: '#f0d7cf',
    borderRadius: 14,
    borderWidth: 1,
    flex: 1,
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  analyticsMetricItem: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: '#f0d7cf',
    borderRadius: 16,
    borderWidth: 1,
    flex: 1,
    minWidth: 120,
    paddingHorizontal: 12,
    paddingVertical: 14,
  },
  analyticsMetricValue: {
    color: '#2f2320',
    fontSize: 22,
    fontWeight: '900',
  },
  analyticsMetricLabel: {
    color: '#806f69',
    fontSize: 12,
    fontWeight: '700',
    marginTop: 4,
  },
  analyticsCard: {
    backgroundColor: '#ffffff',
    borderColor: '#f0d7cf',
    borderRadius: 20,
    borderWidth: 1,
    marginTop: 16,
    padding: 16,
  },
  analyticsCardTitle: {
    color: '#2f2320',
    fontSize: 17,
    fontWeight: '800',
  },
  analyticsEmptyText: {
    color: '#806f69',
    lineHeight: 21,
    marginTop: 10,
  },
  analyticsBarItem: {
    marginTop: 14,
  },
  analyticsBarLabelRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  analyticsTagText: {
    color: '#a05d6f',
    fontSize: 14,
    fontWeight: '800',
  },
  analyticsCountText: {
    color: '#806f69',
    fontSize: 12,
    fontWeight: '700',
  },
  analyticsBarTrack: {
    backgroundColor: '#f6e7e2',
    borderRadius: 999,
    height: 10,
    marginTop: 8,
    overflow: 'hidden',
  },
  analyticsBarFill: {
    backgroundColor: '#d94f70',
    borderRadius: 999,
    height: '100%',
  },
  analyticsInsightText: {
    color: '#5d4e49',
    fontSize: 15,
    fontWeight: '700',
    lineHeight: 22,
    marginTop: 10,
  },
  analyticsTopPostItem: {
    backgroundColor: '#fff7f3',
    borderColor: '#f0d7cf',
    borderRadius: 14,
    borderWidth: 1,
    marginTop: 12,
    padding: 12,
  },
  analyticsTopPostTitle: {
    color: '#2f2320',
    fontSize: 15,
    fontWeight: '800',
    marginBottom: 6,
  },
  tabBar: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderTopColor: '#efd8d0',
    borderTopWidth: 1,
    flexDirection: 'row',
    gap: 6,
    justifyContent: 'space-around',
    paddingHorizontal: 8,
    paddingVertical: 8,
  },
  tabButton: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    minHeight: 58,
    minWidth: 72,
    paddingHorizontal: 10,
    paddingVertical: 14,
    position: 'relative',
  },
  tabBadge: {
    backgroundColor: '#d94f70',
    borderColor: '#ffffff',
    borderRadius: 5,
    borderWidth: 2,
    height: 10,
    position: 'absolute',
    right: 18,
    top: 8,
    width: 10,
  },
  tabText: {
    color: '#8a7771',
    fontSize: 15,
    fontWeight: '700',
  },
  tabTextActive: {
    color: '#d94f70',
  },
  createButton: {
    alignItems: 'center',
    backgroundColor: '#d94f70',
    borderRadius: 32,
    height: 64,
    justifyContent: 'center',
    marginTop: -28,
    width: 64,
  },
  createButtonText: {
    color: '#ffffff',
    fontSize: 32,
    lineHeight: 36,
  },
});

export type MarkdownStyle = {
  body?: object;
  heading1?: object;
  heading2?: object;
  heading3?: object;
  heading4?: object;
  paragraph?: object;
  strong?: object;
  em?: object;
  code_inline?: object;
  code_block?: object;
  blockquote?: object;
  bullet_list?: object;
  ordered_list?: object;
  list_item?: object;
  link?: object;
  fence?: object;
};

export const markdownStyles = {
  body: {
    color: '#3d302c',
    fontSize: 16,
    lineHeight: 26,
    marginTop: 20,
  },
  heading1: {
    color: '#2f2320',
    fontSize: 28,
    fontWeight: '800',
    marginTop: 22,
    marginBottom: 10,
  },
  heading2: {
    color: '#2f2320',
    fontSize: 22,
    fontWeight: '800',
    marginTop: 18,
    marginBottom: 8,
  },
  heading3: {
    color: '#2f2320',
    fontSize: 19,
    fontWeight: '800',
    marginTop: 16,
    marginBottom: 8,
  },
  heading4: {
    color: '#5d4e49',
    fontSize: 17,
    fontWeight: '700',
    marginTop: 14,
    marginBottom: 8,
  },
  paragraph: {
    marginTop: 0,
    marginBottom: 12,
  },
  bullet_list: {
    marginBottom: 12,
  },
  ordered_list: {
    marginBottom: 12,
  },
  blockquote: {
    borderLeftColor: '#d94f70',
    borderLeftWidth: 4,
    color: '#6a5a55',
    marginBottom: 12,
    paddingLeft: 12,
  },
  code_inline: {
    backgroundColor: '#f6e7e2',
    borderRadius: 6,
    color: '#7b2c3a',
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  code_block: {
    backgroundColor: '#2f2320',
    borderRadius: 14,
    color: '#fef7f3',
    marginBottom: 12,
    padding: 14,
  },
  fence: {
    backgroundColor: '#2f2320',
    borderRadius: 14,
    color: '#fef7f3',
    marginBottom: 12,
    padding: 14,
  },
} as const;
